/*
 * Conteúdo legal apresentado dentro do aplicativo. A versão é enviada à
 * Cloud Function no aceite para que o registro no servidor seja auditável.
 */
window.EXIFRANK_LEGAL_DOCUMENTS = {
    version: "2026-08-24",
    updatedAt: "24 de agosto de 2026",
    supportEmail: "suporteexifrank@gmail.com",
    terms: {
        title: "Termos de Uso",
        intro: "Estes Termos regulam o uso do site, aplicativo desktop e serviços vinculados ao ExifRank.",
        sections: [
            ["1. Aceite e escopo", "Ao marcar o aceite no primeiro acesso, criar uma conta, instalar ou usar o ExifRank, você declara que leu e concorda com estes Termos e com a Política de Privacidade. Se não concordar, não utilize o serviço. A versão aceita, a data e a hora são registradas em nossos sistemas para fins de comprovação."],
            ["2. O que o ExifRank oferece", "O ExifRank é uma ferramenta para organização de projetos, edição e processamento local de metadados EXIF, apoio à rotina de SEO Local e geração de relatórios. O serviço auxilia o trabalho profissional, mas não garante posicionamento em mecanismos de busca, resultados comerciais ou aprovação por plataformas de terceiros."],
            ["3. Conta e uso responsável", "Você deve fornecer dados verdadeiros, manter o acesso à conta protegido e usar o aplicativo apenas de forma lícita. Você é responsável pelos dados, imagens, endereços, coordenadas, marcas e informações de clientes inseridos no ExifRank, inclusive por ter a autorização necessária para tratá-los."],
            ["4. Plano gratuito e Premium", "O plano gratuito possui os limites exibidos no aplicativo. O Premium libera os recursos indicados no momento da contratação, enquanto a assinatura estiver ativa e regular. A licença Premium é pessoal, não exclusiva, não transferível e vinculada a uma conta autenticada."],
            ["5. Assinatura, cobrança e cancelamento", "A assinatura Premium é mensal e o preço, a periodicidade e as condições aplicáveis são exibidos antes da confirmação da compra. O pagamento e a gestão da assinatura são processados pelo Mercado Pago; o ExifRank não recebe nem armazena os dados completos do seu cartão. Para cancelar, use os meios disponibilizados pelo Mercado Pago ou escreva para suporteexifrank@gmail.com. Eventuais pedidos de arrependimento, cancelamento ou reembolso serão analisados conforme a legislação aplicável e as condições informadas no checkout."],
            ["6. Licença por dispositivo", "Para proteger a licença Premium, o aplicativo pode vincular a conta a um identificador técnico do computador. A utilização é limitada a um dispositivo ou ambiente operacional autorizado por licença, salvo ajuste liberado pelo suporte. Não tente contornar controles de licença, compartilhar credenciais, interferir no funcionamento do aplicativo ou realizar engenharia reversa, exceto quando a legislação aplicável permitir expressamente."],
            ["7. Serviços de terceiros", "Alguns recursos dependem de serviços de terceiros, como Firebase/Google, Mercado Pago e, quando você optar por usar integrações assistidas, provedores de IA. Esses serviços possuem regras e disponibilidade próprias. O ExifRank não controla mudanças, indisponibilidades ou decisões tomadas por eles."],
            ["8. Disponibilidade, dados e segurança", "Buscamos manter o serviço disponível e seguro, mas interrupções, atualizações, falhas de rede e limitações do seu computador podem ocorrer. Mantenha cópias de segurança dos seus arquivos e confira informações e relatórios antes de usá-los com clientes. Nada nestes Termos exclui direitos que a legislação de defesa do consumidor não permita excluir."],
            ["9. Suspensão e atualizações", "Podemos corrigir, atualizar ou descontinuar recursos por razões técnicas, de segurança, legais ou operacionais. Em caso de violação relevante destes Termos ou uso que gere risco ao serviço, poderemos restringir o acesso de forma proporcional e, quando cabível, comunicar o motivo."],
            ["10. Alterações e contato", "Podemos atualizar estes Termos para refletir mudanças no aplicativo, no serviço ou na legislação. Alterações relevantes serão apresentadas no app e poderão exigir novo aceite. Para dúvidas, suporte, cancelamento ou solicitações relacionadas a estes Termos, escreva para suporteexifrank@gmail.com. Aplicam-se as leis brasileiras, preservados os direitos e foros definidos pela legislação aplicável."]
        ]
    },
    privacy: {
        title: "Política de Privacidade",
        intro: "Esta Política explica como o ExifRank trata dados pessoais ao disponibilizar o site, o aplicativo desktop e os serviços em nuvem relacionados.",
        sections: [
            ["1. Quem trata os dados e como falar conosco", "O ExifRank é responsável pelo tratamento descrito nesta Política no contexto do aplicativo e de seus serviços. Para dúvidas, solicitações de privacidade ou exercício de direitos, entre em contato pelo e-mail suporteexifrank@gmail.com."],
            ["2. Dados que podemos tratar", "Podemos tratar dados de conta, como e-mail, nome e foto pública quando fornecidos pelo provedor de login; dados de uso e suporte; dados dos projetos que você optar por sincronizar, como nomes de clientes, endereços, telefones, coordenadas e metadados; identificadores técnicos necessários à licença Premium, como o Hardware ID; dados de assinatura e status de pagamento; e o registro do aceite destes documentos, com versão e data/hora."],
            ["3. Arquivos e processamento local", "O processamento de imagens, vídeos e metadados EXIF ocorre no seu computador. Os arquivos selecionados e o conteúdo deles não são enviados ao ExifRank apenas pelo ato de processá-los localmente. Informações de projeto que você optar por sincronizar podem ser gravadas na infraestrutura em nuvem descrita abaixo."],
            ["4. Finalidades e bases legais", "Usamos os dados para autenticar a conta, fornecer e sincronizar funcionalidades, executar a assinatura, prevenir fraude e uso indevido, atender o suporte, cumprir obrigações legais e melhorar a segurança do serviço. Conforme o caso, o tratamento se apoia na execução do contrato, no cumprimento de obrigação legal, no exercício regular de direitos, em interesses legítimos de segurança e, quando aplicável, no seu consentimento."],
            ["5. Compartilhamento e operadores", "Usamos fornecedores que atuam para viabilizar o serviço, como Firebase e Google Cloud para autenticação, banco de dados e infraestrutura, e Mercado Pago para o checkout e a gestão de pagamentos recorrentes. Se você usar recursos que dependam de integração externa, os dados estritamente necessários poderão ser enviados ao provedor escolhido. Não vendemos dados pessoais ou dados de projetos para publicidade."],
            ["6. Pagamentos", "O pagamento da assinatura é realizado no ambiente do Mercado Pago. O ExifRank recebe informações necessárias para liberar e administrar o acesso, como e-mail de referência, identificadores da assinatura, situação e datas de cobrança. Não armazenamos número completo de cartão, código de segurança ou credenciais de pagamento."],
            ["7. Armazenamento e segurança", "Dados de projetos podem ficar no armazenamento local do seu computador e, quando a sincronização estiver ativa, no Firestore. Aplicamos controles de acesso e medidas técnicas razoáveis compatíveis com a operação do serviço. Nenhum ambiente conectado à internet é completamente isento de riscos; por isso, também recomendamos que você proteja sua conta e mantenha cópias de segurança."],
            ["8. Retenção e transferências", "Mantemos os dados pelo tempo necessário para prestar o serviço, cumprir obrigações legais, resolver solicitações e proteger direitos. A infraestrutura de fornecedores pode envolver processamento fora do Brasil, com salvaguardas adotadas pelos respectivos provedores. Dados locais podem permanecer no seu computador até que você os exclua."],
            ["9. Seus direitos", "Nos termos da LGPD, você pode solicitar confirmação do tratamento, acesso, correção, anonimização, bloqueio, eliminação quando aplicável, portabilidade, informações sobre compartilhamentos, revogação de consentimento e revisão das hipóteses legais. Para isso, envie um pedido para suporteexifrank@gmail.com. Podemos solicitar informações para confirmar sua identidade e proteger sua conta."],
            ["10. Menores e atualizações", "O ExifRank não é direcionado a menores de idade e não busca coletar intencionalmente seus dados. Esta Política pode ser atualizada para refletir mudanças no serviço ou na legislação. Uma nova versão será disponibilizada no site e no aplicativo; quando necessário, pediremos novo aceite."]
        ]
    }
};
